# Autogenerated wrapper script for cmark_jll for i686-w64-mingw32
export cmark, libcmark

JLLWrappers.@generate_wrapper_header("cmark")
JLLWrappers.@declare_library_product(libcmark, "libcmark.dll")
JLLWrappers.@declare_executable_product(cmark)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libcmark,
        "bin\\libcmark.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        cmark,
        "bin\\cmark.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
